# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_vision_interaction/kinect_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class kinect_msg(genpy.Message):
  _md5sum = "7d063af4b46c588d600951ce9d186617"
  _type = "imu_vision_interaction/kinect_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64[5] im_screw_probs_1
float64[5] im_screw_probs_2
float64[5] im_screw_probs_3
float64[5] im_screw_probs_4
float64[5] tally
bool safe_move"""
  __slots__ = ['im_screw_probs_1','im_screw_probs_2','im_screw_probs_3','im_screw_probs_4','tally','safe_move']
  _slot_types = ['float64[5]','float64[5]','float64[5]','float64[5]','float64[5]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       im_screw_probs_1,im_screw_probs_2,im_screw_probs_3,im_screw_probs_4,tally,safe_move

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(kinect_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.im_screw_probs_1 is None:
        self.im_screw_probs_1 = [0.] * 5
      if self.im_screw_probs_2 is None:
        self.im_screw_probs_2 = [0.] * 5
      if self.im_screw_probs_3 is None:
        self.im_screw_probs_3 = [0.] * 5
      if self.im_screw_probs_4 is None:
        self.im_screw_probs_4 = [0.] * 5
      if self.tally is None:
        self.tally = [0.] * 5
      if self.safe_move is None:
        self.safe_move = False
    else:
      self.im_screw_probs_1 = [0.] * 5
      self.im_screw_probs_2 = [0.] * 5
      self.im_screw_probs_3 = [0.] * 5
      self.im_screw_probs_4 = [0.] * 5
      self.tally = [0.] * 5
      self.safe_move = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_5d().pack(*self.im_screw_probs_1))
      buff.write(_get_struct_5d().pack(*self.im_screw_probs_2))
      buff.write(_get_struct_5d().pack(*self.im_screw_probs_3))
      buff.write(_get_struct_5d().pack(*self.im_screw_probs_4))
      buff.write(_get_struct_5d().pack(*self.tally))
      buff.write(_get_struct_B().pack(self.safe_move))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 40
      self.im_screw_probs_1 = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 40
      self.im_screw_probs_2 = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 40
      self.im_screw_probs_3 = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 40
      self.im_screw_probs_4 = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 40
      self.tally = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 1
      (self.safe_move,) = _get_struct_B().unpack(str[start:end])
      self.safe_move = bool(self.safe_move)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.im_screw_probs_1.tostring())
      buff.write(self.im_screw_probs_2.tostring())
      buff.write(self.im_screw_probs_3.tostring())
      buff.write(self.im_screw_probs_4.tostring())
      buff.write(self.tally.tostring())
      buff.write(_get_struct_B().pack(self.safe_move))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 40
      self.im_screw_probs_1 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 40
      self.im_screw_probs_2 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 40
      self.im_screw_probs_3 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 40
      self.im_screw_probs_4 = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 40
      self.tally = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 1
      (self.safe_move,) = _get_struct_B().unpack(str[start:end])
      self.safe_move = bool(self.safe_move)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
